### ISSUE TITLE
Problema di bilanciamento

### ISSUE THREAD

**Issue by andreacoradi** [alessandro-bugatti/batteri#1]
Risulta che il primo batterio della lista avendo sempre la prima mossa, cresca più degli altri.
Si potrebbe far fare la prima mossa al batterio più svantaggiato, oppure semplicemente random.
Dal Gruppo Coradi, Girardi, Astori

**Comment by alessandro-bugatti** [comment]
Vero, però questo nel lungo periodo non sembra essere un grande vantaggio, poichè mi sembra sia un vantaggio solo nel caso due batteri si trovino alla stessa distanza dalla pillola di cibo e ci si dirigano con un percorso di uguale lunghezza. Inoltre, poichè non vince un solo batterio ma una popolazione, nel lungo periodo i singoli batteri dei diversi tipi risultano mescolati (credo), e quindi si torna sempre al punto di partenza di "nessun vantaggio significativo"
Volendo comunque evitare quel problema proponete delle soluzioni ragionevoli, tenendo conto che devono essere sufficientemente leggere da un punto di vista computazionale, poichè la lista può contenere decine di migliaia di batteri e viene aggiornata ogni pochi millisecondi. Quelle due già proposte (più svantaggiato, random) definitele meglio altrimenti non si possono valutare. Ricordo che anche questi interventi verranno valutati (solo in **positivo**)
