### ISSUE TITLE
Batteri figli cancellati

### ISSUE THREAD

**Issue by cyber-land** [alessandro-bugatti/batteri#10]
Il recupera nomi del mainForm recupera tutte le classi compilate (.class) anche di batteri cui sorgente è stato cancellato, questo comportamento inaspettato è facilmente risolvibile andando a cancellare i file compilati in build/batteri_figli ma potrebbe non essere immediato per tutti
Si potrebbe risolvere andando a controllare se esiste il corrispettivo nomeDellaClasse.java nella cartella src/batteri_figli
Problema esposto a nome del gruppo non personale

**Comment by alessandro-bugatti** [comment]
In realtà non è un problema, perchè dipende dal modo di funzionare di NetBeans, non del progetto in sè. Quindi direi che il problema si può risolvere semplicemente usando la funzionalità di Clean di NetBeans
