### ISSUE TITLE
dimensioni variabili del terreno

### ISSUE THREAD

**Issue by cyber-land** [alessandro-bugatti/batteri#11]
la colonna destra che contiene i bottoni ed i batteri partecipanti potrebbe nascondere parte del terreno quando si ingrandisce a causa dei nomi e dei valori che deve contenere, lo stesso si verifica anche quando la colonna si restringe, mostrano una piccola area esterna al terreno di gioco

**Comment by alessandro-bugatti** [comment]
Vero, in generale non è un problema, oltre al fatto che sia brutto esteticamente non crea danni alla simulazione, se ho tempo gli darò un'occhiata, però essendo una libreria che non uso da un po' non so quanto riuscirò a fare senza perderci troppo tempo, vediamo.

**Comment by alessandro-bugatti** [comment]
@ketgwa Ho fatto una piccola modifica alla dimensione della finestra in modo che il problema non possa presentarsi più, a meno di nomi di classi estremamente lunghi. Trovi il nuovo codice in [questo branch](https://github.com/alessandro-bugatti/batteri/tree/gestione_pannello), provalo e se va tutto bene poi faccio un merge in master.

**Comment by cyber-land** [comment]
Ricordo che i batteri nel video tornano indietro quando arrivano ad una distanza di 10 pixel dal bordo
Il video  mostra come il terreno sia corretto a nord, est e ovest, ma a sud c'è una zona tagliata, grande appossimativamente 50px
https://drive.google.com/file/d/1xtFgVFQWeioY3WXv2o8oylpfZzgqt2pf/view?usp=sharing

**Comment by alessandro-bugatti** [comment]
Mi viene da pensare che potrebbe dipendere dai controlli che fai nel tuo codice dei batteri, se sei invece sicuro che dipenda dal codice dell'applicazione principale, fammi sapere che appena riesco gli darò un'occhiata

**Comment by cyber-land** [comment]
Non credo che il mio codice c'entri, comunque gli allego il link anche di questo se vuole controllare
https://github.com/Fusari303/batteri/blob/ght/src/batteri_figli/TheStrategist.java

**Comment by alessandro-bugatti** [comment]
Non ho controllato, ma siccome il problema non si manifesta nei Tontini, continuo a credere che il problema sia nel tuo codice, devi convincermi con qualche argomento solido...

**Comment by cyber-land** [comment]
Questo video mostra come alcune volte vengono creati dei quadrati di cibo nell'area nascosta a sud
https://drive.google.com/file/d/1pFfaxVPiniq9hbDTRXlsowUF1__fqOAr/view?usp=sharing

**Comment by alessandro-bugatti** [comment]
Adesso dovrebbe funzionare tutto correttamente, ho chiuso con #13
