### ISSUE TITLE
Problema con il giallo

### ISSUE THREAD

**Issue by GhostyJade** [alessandro-bugatti/batteri#2]
All'aggiunta del quarto batterio, viene assegnato come colore il giallo, rendendolo indistinguibile dallo sfondo.

![Schermata 2019-03-16 alle 10 29 48](https://user-images.githubusercontent.com/38327334/54473332-9a5efa80-47d6-11e9-919b-465aaab15f3d.png)

**Comment by andreacoradi** [comment]
secondo me il bianco è un colore migliore per lo sfondo

**Comment by alessandro-bugatti** [comment]
> 
> 
> secondo me il bianco è un colore migliore per lo sfondo

Puoi provare a farlo bianco per vedere come viene? Inizialmente era bianco, se l'ho cambiato magari c'era un motivo, forse per la proiezione in aula, comunque se dalle tue prove mi confermi che bianco si vede meglio lo rimetto bianco (@Andrea-C1201 e tolgo WHITE e non YELLOW dalla lista dei colori)

**Comment by andreacoradi** [comment]
Lo sto provando da qualche giorno e confermo che bianco sarebbe meglio come colore per lo sfondo
