### ISSUE TITLE
Possibile idea sulla gestione delle eccezioni causate dai batteri.

### ISSUE THREAD

**Issue by GhostyJade** [alessandro-bugatti/batteri#3]
Buongiorno. Stavo facendo alcuni test e mi è tornato alla mente il fatto che se un batterio dovesse generare un'eccezione, tutto il programma andrebbe in crash.
Stavo pensando, quindi, quando le classi vengono caricate all'interno del programma, di aggiungere un singolo thread per ogni batterio, in modo che se un batterio dovesse generare un'eccezione, si possa fermare quel thread e rimuovere il batterio che causa problemi direttamente dal programma.

**Comment by alessandro-bugatti** [comment]
Sarebbe una possibilità, ma non l'ho mai testata. Da una ricerca sommaria che avevo fatto sembrerebbero esserci alcuni potenziali problemi:
* il numero massimo di thread contemporanei: Java, in dipendenza dalla versione, può supportare un numero thread finito, che (ma qui si potrebbe investigare meglio) è dell'ordine delle decine di migliaia. Le simulazioni di gara si spingono ad avere decine di migliaia di batteri, quindi potrebbe essere lanciata un'eccezione OutOfMemoryError, che generalmente non è gestibile in modo sensato se non terminando il programma
* all'aumentare del numero di thread, il tempo di creazione aumenta e questo potrebbe comportare dei problemi per la fluidità della simulazione, quindi introdurre dei problemi di performance (seri o meno bisognerebbe provare)
* un'altra cosa di cui sono meno certo, ma che andrebbe presa in considerazione, è che ci sarebbe un notevole trashing della memoria cache, che di nuovo potrebbe portare dei rallentamenti
* un'altra possibilità per evitare almeno il crash del programma, sarebbe quella di intercettare le eccezioni lanciate dai batteri, che tipicamente sono di tipo ArrayOutOfBound. Questo non è mai stato fatto ma sarebbe la soluzione più semplice per evitare il crollo del programma. Il motivo per cui non è stato fatto è che inizialmente questo programma era scritto in C++ e usava una matrice nativa, quindi l'uscita dalla matrice non genera eccezioni, ma porta solo il programma in uno stato indeterminato (potrebbe crollare ma anche no).

Detto questo ci sarebbero due motivi principali per introdurre i thread:
- non ci sarebbe più il limite delle circa 100 istruzioni, poichè essendo ogni batterio un thread separato, ad ognuno verrebbe allocato uno slot di tempo uguale a quello di ogni altro, quindi chi usa meno istruzioni potrebbe fare un singolo spostamento ogni slot temporale, mentre chi ne usa di più avrebbe bisogno di più slot temporali per portare a compimento un singolo spostamento, usando quindi più *energia*.
- se un batterio entra in un ciclo infinito adesso freeza tutta l'applicazione, se invece fosse in un thread separato il problema sarebbe solo suo.

Conclusione: se qualcuno, non solo @Andrea-C1201 , vuole forkare il repository e modificare l'applicazione per supportare i thread, è ben accetto, tanto più che mi sembra che abbiate iniziato i thread in TPI, dopodichè faccia una pull request e vediamo se accettarla.
Per la sfida di domani ormai è troppo tardi e quindi tutto rimane invariato.

**Comment by alessandro-bugatti** [comment]
Chiuso poichè nel frattempo sono state seguite altre strade
