### ISSUE TITLE
I batteri possono abusare lo spawn del cibo

### ISSUE THREAD

**Issue by andreacoradi** [alessandro-bugatti/batteri#4]
### Essendo il riferimento di food accessibile ai batteri_figli è possibile alterare la modalità di spawn del cibo (non la frequenza). 

Food all'interno di un batterio dovrebbe essere usato solamente per ottenere le dimensioni della matrice, far si che food non sia accessibile ai batteri_figli darebbe senso a metodi come `ControllaCibo(x,y)`, che possono essere bypassati con `food.IsFood(x,y)` e la creazione di costanti come **WIDTH** e **HEIGHT** risolverebbe il problema di ottenere le dimensioni. Il problema è che un batterio per clonarsi deve passare il suo riferimento al cibo e quindi non è così diretta come soluzione. 

Si vorrebbe evitare il seguente codice:
`protected void Sposta(){
       food.cornerDistribution(50, 50); } `

Esempio di abuso di food da parte dei batteri_figli:
![immagine](https://user-images.githubusercontent.com/10401120/55406874-3d48a000-555d-11e9-9656-d261f71eaa35.png)

**Comment by alessandro-bugatti** [comment]
Il problema, come dici tu, è che devo avere un riferimento al cibo per la clonazione, solo che se ho quel riferimento poi ci posso fare quello che voglio, poichè, se nascondessi qualcosa, anche il Terrain poi non riuscirebbe a usarlo. La prima idea che mi è venuto è di non usare il costruttore per clonare il batterio, ma il metodo clone, in modo da non aver bisogno di passare il riferimento, solo che succede qualcosa di brutto, che ti invito a pensare. Ho creato il branch *issue4* per sperimentare una soluzione, se vuoi dacci un'occhiata e vedi se riesci a suggerire qualcosa

**Comment by alessandro-bugatti** [comment]
@Andry01k prova a vedere come funziona adesso e se è risolto il problema dell'abuso di cibo. Se testi un attimo e ti sembra accettabile possiamo chiudere l'issue e fare il merge

**Comment by andreacoradi** [comment]
@alessandro-bugatti si sembra accettabile. Aggiungerei in caso un metodo getSalute() perchè mi sembra che alcuni batteri sfruttino questo valore per decidere se muoversi o meno, potrei sbagliarmi. Però questo problema è messo a posto quindi si può chiudere
